inherit_gem:
  wetransfer_style: ruby/default.yml
AllCops:
  TargetRubyVersion: 2.3
Layout/FirstMethodArgumentLineBreak:
  Enabled: false
Layout/FirstMethodParameterLineBreak:
  Enabled: false
Layout/HeredocIndentation:
  Enabled: false # Newer rubocop enforces heredocs that are only available in 2.3+
Style/GlobalVars:
  Exclude:
      - qa/*.rb
      - spec/spec_helper.rb
      - spec/support/zip_inspection.rb
