inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 120
  Exclude:
    - lib/zip_tricks/zip_writer.rb

AllCops:
  Exclude:
    - spec/**/*.rb
    - zip_tricks.gemspec
    - Gemfile
    - Rakefile
    - vendor/**/*
    - julik_scratchpad/**/*

Style/ClassAndModuleChildren:
  Enabled:
    false

# "begin; ... rescue; end " without saying that we only rescue StandardError and below.
# Can be debated, but I think it is reasonable to expect any Rubyist to know what errors
# the standard rescue clause covers.
Style/RescueStandardError:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

# We use % all over and nothing ever came out of it
Style/FormatString:
  Enabled: false

# We have classes with methods having long bodies. We apply a lot of literal small
# operations which have to be applied in one locality specifically. Additionally,
# class length is a bit of a boilerplate metric
Metrics/ClassLength:
  Enabled: false

# Idem. We have quite some methods that do a lot of small writes/reads in rapid
# succession - not because those methods have high cyclomatic complexity, but
# because they perform a single operation consisting of many sequential small
# ones.
Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - examples/rack_application.rb
    - lib/zip_tricks/file_reader.rb
    - lib/zip_tricks/remote_io.rb
    - lib/zip_tricks/streamer.rb
    - qa/support.rb
    - lib/zip_tricks/zip_writer.rb

Metrics/BlockLength:
  Exclude:
    - lib/zip_tricks/file_reader.rb

Layout/MultilineOperationIndentation:
  Exclude:
    - lib/zip_tricks/file_reader.rb
    - lib/zip_tricks/zip_writer.rb

Metrics/ParameterLists:
  Exclude:
    - lib/zip_tricks/streamer.rb
    - lib/zip_tricks/zip_writer.rb

Style/GlobalVars:
  Exclude:
    - qa/generate_test_files.rb
    - qa/support.rb

# The advice this cop gives varies depending on the Ruby version,
# so no - I will not be following two conflicting recommendations.
Style/MutableConstant:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/ZeroLengthPredicate:
  Enabled: false # Does not work for StringIOs

Naming/ConstantName:
  Exclude:
    - lib/zip_tricks/file_reader.rb
    - lib/zip_tricks/zip_writer.rb

Layout/CommentIndentation:
  Exclude:
    - lib/zip_tricks/zip_writer.rb

Style/RedundantParentheses:
  Exclude:
    - lib/zip_tricks/zip_writer.rb

Metrics/PerceivedComplexity:
  Exclude:
    - lib/zip_tricks/zip_writer.rb
    - lib/zip_tricks/streamer.rb

Layout/AlignParameters:
  Exclude:
    - lib/zip_tricks/zip_writer.rb

Style/ConditionalAssignment:
  Exclude:
    - lib/zip_tricks/zip_writer.rb

Layout/ExtraSpacing:
  Exclude:
    - lib/zip_tricks/zip_writer.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - lib/zip_tricks/zip_writer.rb

Layout/LeadingCommentSpace:
  Exclude:
    - lib/zip_tricks/zip_writer.rb

Lint/UselessAssignment:
  Exclude:
    - lib/zip_tricks/zip_writer.rb
    - lib/zip_tricks/streamer.rb

Style/Documentation:
  Exclude:
    - lib/zip_tricks/block_deflate.rb
    - lib/zip_tricks/block_write.rb
    - lib/zip_tricks/file_reader.rb

Style/GuardClause:
  Exclude:
    - lib/zip_tricks/file_reader.rb    

Style/StructInheritance:
  Exclude:
    - lib/zip_tricks/streamer/entry.rb

