inherit_gem:
  wetransfer_style: ruby/default.yml
AllCops:
  TargetRubyVersion: 2.1
Layout/FirstMethodArgumentLineBreak:
  Enabled: false
Layout/FirstMethodParameterLineBreak:
  Enabled: false
Style/GlobalVars:
  Exclude:
      - qa/*.rb
      - spec/spec_helper.rb
      - spec/support/zip_inspection.rb
Layout/IndentHeredoc:
  Enabled: false
